### ISSUE TITLE
InchiKey Identifiers

### ISSUE THREAD

**Issue by marvinm2** [marvinm2/AOPWikiRDF#1]
https://github.com/marvinm2/AOPWikiRDF/blob/3c284d5def4259d3d7fe65ce51c30738313e1afe/AOPWiki_XML_to_Ttl.py#L96-L99

We need a proper link for the inchi-keys that are present in the AOP Wiki.

**Comment by egonw** [comment]
For the InChIKey you can use the CHEMINF ontology (see https://doi.org/10.1371/JOURNAL.PONE.0025513): http://semanticscience.org/resource/CHEMINF_000059 (see https://github.com/semanticchemistry/semanticchemistry/blob/c211764a914856ef9b7f8f9f54c31b53147fb5fb/ontology/cheminf-core.owl#L1129-L1140)
