### ISSUE TITLE
DSStox IDs without linkout

### ISSUE THREAD

**Issue by marvinm2** [marvinm2/AOPWikiRDF#2]
https://github.com/marvinm2/AOPWikiRDF/blob/3c284d5def4259d3d7fe65ce51c30738313e1afe/AOPWiki_XML_to_Ttl.py#L102-L103

DSStox IDs are not registered on identifiers.org. Need to find another way to link to the right URLs.

**Comment by egonw** [comment]
Added now: http://semanticscience.org/resource/CHEMINF_000568

**Comment by egonw** [comment]
just use the IRI... I just pinged Michel on Twitter about it...
